# ─────────────────────────────────────────────────────────────────────────────
# build_dashboard_app.R
# Bundles app/app.R and the aggregate CSV into a Shinylive code block, written
# to docs/_dashboard_app.qmd and pulled into docs/dashboard.qmd via include.
# Also copies the CSV to app/ for local `shiny::runApp("app")` testing.
#
# Shinylive apps run in the browser, so the data has to ship inside the page.
# Embedding it as a `## file:` entry means the build-time aggregate (and only
# that) becomes part of the static site — no API call from the browser.
#
# Run after fetch_and_aggregate.R:
#   Rscript scripts/build_dashboard_app.R
# ─────────────────────────────────────────────────────────────────────────────

APP_PATH     <- "app/app.R"
DATA_PATH    <- "data/processed_summary.csv"
INCLUDE_PATH <- "docs/_dashboard_app.qmd"

if (!file.exists(DATA_PATH)) {
  stop(DATA_PATH, " not found. Run scripts/fetch_and_aggregate.R first.", call. = FALSE)
}

app_lines  <- readLines(APP_PATH, warn = FALSE)
data_lines <- readLines(DATA_PATH, warn = FALSE)

block <- c(
  "<!-- Generated by scripts/build_dashboard_app.R — do not edit or commit. -->",
  "",
  "```{shinylive-r}",
  "#| standalone: true",
  "#| viewerHeight: 900",
  "## file: app.R",
  app_lines,
  "",
  "## file: processed_summary.csv",
  "## type: text",
  data_lines,
  "```"
)

writeLines(block, INCLUDE_PATH)
message(sprintf("Wrote %s (%d data rows embedded).", INCLUDE_PATH, length(data_lines) - 1))

# Same data next to app.R, so `shiny::runApp("app")` works for desktop testing.
invisible(file.copy(DATA_PATH, file.path(dirname(APP_PATH), basename(DATA_PATH)), overwrite = TRUE))
